DatPhongDiWEB/DatPhongDiWeb/Models/TypeOfRoom/ChangeStatusTypeOfRoomReq.cs
namespace DatPhongDiWeb.Models.TypeOfRoom
{
    public class ChangeStatusTypeOfRoomReq
    {
        public int  Id { get; set; }
        public int Status { get; set; }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Models/TypeOfRoom/CheckAvailable.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DatPhongDiWeb.Models.TypeOfRoom
{
    public class CheckAvailable
    {
        public int AmountAdults { get; set; }
        public int AmountChild { get; set; }
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime CheckIn { get; set; }
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime CheckOut { get; set; }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Models/TypeOfRoom/CheckTypeOfRoomAvailable.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DatPhongDiWeb.Views.TypeOfRoom
{
    public class CheckTypeOfRoomAvailable
    {
        public int Id { get; set; }
        public DateTime CheckIn { get; set; }
        public DateTime CheckOut { get; set; }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Models/TypeOfRoom/DeleteImageRes.cs
namespace DatPhongDiWeb.Models.TypeOfRoom
{
    public class DeleteImageRes
    {
        public int ImageId { get; set; }
        public string Message { get; set; }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Models/TypeOfRoom/ImageView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DatPhongDiWeb.Models.TypeOfRoom
{
    public class ImageView
    {
        public int ImageId { get; set; }
        public string ImagePath { get; set; }
        public int TypeOfRoomId { get; set; }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Models/TypeOfRoom/RoomTypeDetailView.cs
using System.Collections.Generic;

namespace DatPhongDiWeb.Models.TypeOfRoom
{
    public class RoomTypeDetailView
    {
        public string Name { get; set; }
        public int AmountAdults { get; set; }
        public int AmountChild { get; set; }
        public int PricePerNight { get; set; }
        public int Size { get; set; }
        public int AmountAvailableRoom { get; set; }
        public List<ImageView> Images { get; set; }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Models/TypeOfRoom/SaveImageRes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DatPhongDiWeb.Models.TypeOfRoom
{
    public class SaveImageRes
    {
        public int ImageId { get; set; }
        public string Message { get; set; }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Models/TypeOfRoom/SaveTypeOfRoom.cs
namespace DatPhongDiWeb.Models.TypeOfRoom
{
    public class SaveTypeOfRoom
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public int AmountAdults { get; set; }
        public int AmountChild { get; set; }
        public int PricePerNight { get; set; }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Models/TypeOfRoom/SaveTypeOfRoomReq.cs
namespace DatPhongDiWeb.Models.TypeOfRoom
{
    public class SaveTypeOfRoomReq
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public int AmountAdults { get; set; }
        public int AmountChild { get; set; }
        public int PricePerNight { get; set; }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Models/TypeOfRoom/SaveTypeOfRoomRes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DatPhongDiWeb.Models.TypeOfRoom
{
    public class SaveTypeOfRoomRes
    {
        public int Id { get; set; }
        public string Message { get; set; }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Models/TypeOfRoom/TypeofRoomView.cs
using DatPhongDiWeb.Models.Service;
using DatPhongDiWeb.Models.TypeOfRoomService;
using System;
using System.Collections.Generic;

namespace DatPhongDiWeb.Models.TypeOfRoom
{
    public class TypeofRoomView 
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public string StatusName { get; set; }
        public int AmountAdults { get; set; }
        public int AmountChild { get; set; }
        public int PricePerNight { get; set; }
        public string Message { get; set; }
        public int Size { get; set; }
        public string ImagePath { get; set; }
        public DateTime CheckIn { get; set; }
        public DateTime CheckOut { get; set; }
        public List<ServiceView> ServiceViews { get; set; }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Controllers/TypeOfRoomController.cs
using DatPhongDiWeb.Models.Service;
using DatPhongDiWeb.Models.Status;
using DatPhongDiWeb.Models.TypeOfRoom;
using DatPhongDiWeb.Ultilities;
using DatPhongDiWeb.Views.TypeOfRoom;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;

namespace DatPhongDiWeb.Controllers
{
    public class TypeOfRoomController : Controller
    {
        private readonly IWebHostEnvironment _hostEnvironment;

        public TypeOfRoomController(IWebHostEnvironment hostEnvironment)
        {
            this._hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("/TypeOfRoom/gets")]
        public JsonResult Gets()
        {
            var typeofRoom = ApiHelper<List<TypeofRoomView>>.HttpGetAsync("TypeOfRoom/gets");
            return Json(new { data = typeofRoom });
        }

        [HttpGet]
        [Route("/TypeOfRoom/status/gets")]
        public JsonResult GetStatus()
        {
            var status = ApiHelper<List<StatusView>>.HttpGetAsync($"Status/statusView/{(int)Common.Table.TypeOfRoom}");
            return Json(new { data = status });
        }

        [HttpGet]
        [Route("/TypeOfRoom/getImagesByTypeOfRoomId/{id}")]
        public JsonResult GetImagesByTypeOfRoomId(int id)
        {
            var images = ApiHelper<List<ImageView>>.HttpGetAsync($"image/getImagesByTypeOfRoomId/{id}");
            return Json(new { data = images });
        }

        [HttpPatch]
        [Route("/typeofroom/Save")]
        public JsonResult Save([FromBody] SaveTypeOfRoomReq request)
        {
            var result = ApiHelper<SaveTypeOfRoomRes>.HttpPostAsync($"typeofroom/Save", "PATCH", request);
            return Json(new { data = result });
        }

        [HttpPatch]
        [Route("/typeofroom/delete")]
        public JsonResult Deleted([FromBody] ChangeStatusTypeOfRoomReq req)
        {
            var result = ApiHelper<SaveTypeOfRoomRes>.HttpPostAsync($"typeofroom/ChangeStatus", "POST", req);
            return Json(new { data = result });
        }

        [HttpGet]
        public IActionResult RoomTypeDetail(int Id, DateTime CheckIn, DateTime CheckOut)
        {
            CheckTypeOfRoomAvailable checkTypeOfRoomAvailable = new CheckTypeOfRoomAvailable() { Id = Id, CheckIn = CheckIn, CheckOut = CheckOut };
            var result = ApiHelper<RoomTypeDetailView>.HttpPostAsync($"TypeOfRoom/GetAvailableTypeOfRoom", "POST", checkTypeOfRoomAvailable);
            result.Images = ApiHelper<List<ImageView>>.HttpGetAsync($"image/getImagesByTypeOfRoomId/{Id}");
            return View(result);
        }

        [HttpPost]  
        public IActionResult CheckAvailable(CheckAvailable req)
        {
            ViewBag.CheckIn = req.CheckIn;
            ViewBag.CheckOut = req.CheckOut;
            var data = ApiHelper<List<TypeofRoomView>>.HttpPostAsync($"TypeofRoom/CheckAvailable", "POST", req);
            return View(data);
        }

        [HttpGet]
        [Route("/typeofroom/GetServiceByRoomtypeId/{id}")]
        public JsonResult GetServiceByRoomtypeId(int id)
        {
            var result = ApiHelper<List<ViewServiceByRoomTypeId>>.HttpGetAsync($"TypeOfRoom/getservicebyroomtypeid/{id}");
            return Json(new { data = result });
        }

        [HttpGet]
        [Route("/TypeOfRoom/DeleteImages/{imageId}/{imgpath}")]
        public JsonResult DeleteImages(int imageId, string imgpath)
        {
            var result = ApiHelper<DeleteImageRes>.HttpPostAsync($"image/delete/{imageId}", "POST", new object { });
            if (result.ImageId > 0)
            {
                string DelPath = Path.Combine(_hostEnvironment.WebRootPath, "images", imgpath);
                System.IO.File.Delete(DelPath);
            }
            return Json(new { data = result });
        }

        [HttpPost]
        [Route("/typeofroom/UploadImages")]
        public JsonResult UploadImages(List<IFormFile> Files, int TypeOfRoomId)
        {
            int CountUploadSuccess = 0;
            foreach (var item in Files)
            {
                string pathstr = UploadedFile(item);
                ImageView imageView = new ImageView()
                {
                    ImageId = 0,
                    ImagePath = pathstr,
                    TypeOfRoomId = TypeOfRoomId
                };
                SaveImageRes result = ApiHelper<SaveImageRes>.HttpPostAsync($"image/save", "POST", imageView);

                if (result.ImageId > 0)
                    CountUploadSuccess++;
            }
            return Json(new { data = CountUploadSuccess });
        }

        private string UploadedFile(IFormFile iformfile_path)
        {
            string uniqueFileName = null;

            if (iformfile_path != null)
            {
                string uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + iformfile_path.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using var fileStream = new FileStream(filePath, FileMode.Create);
                iformfile_path.CopyTo(fileStream);
            }
            return uniqueFileName;
        }
    }
}

DatPhongDiWEB/DatPhongDiWeb/Views/TypeOfRoom/CheckAvailable.cshtml
@model IEnumerable<DatPhongDiWeb.Models.TypeOfRoom.TypeofRoomView>

@{
    var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
    Layout = "_LayoutThemesHotelBootraps";
}
<!-- banner -->
<section class="hero-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="hero-text">
                    <h1 style="color: lawngreen">STVK Hotel</h1>
                    <p style="color: black; font-size: 150%; line-height: 1">
                        Đừng chần chờ gì nữa! Hãy đặt niềm tin của bạn cho chúng tôi. Bạn sẽ không phải thất vọng về chất lượng của khách sạn STVK đem lại.
                        Booking ngay để nhận những ưu đãi chưa từng có!
                    </p>
                    <a href="#" class="primary-btn" style="color: black; font-size: 150%">Khám phá bây giờ</a>
                </div>
            </div>
            <div class="col-xl-4 col-lg-5 offset-xl-2 offset-lg-1">
                @await Html.PartialAsync("_FormCheckAvailable", new DatPhongDiWeb.Models.TypeOfRoom.CheckAvailable()
           {
               CheckIn = DateTime.Today,
               CheckOut = DateTime.Today.AddDays(1)
           })
            </div>
        </div>
    </div>
    <div class="hero-slider owl-carousel">
        <div class="hs-item set-bg" data-setbg="/sona-master/img/banner5.jpeg"></div>
        <div class="hs-item set-bg" data-setbg="/sona-master/img/banner2.jpg"></div>
        <div class="hs-item set-bg" data-setbg="/sona-master/img/banner3.jpg"></div>
    </div>
</section>
<!--end banner -->

<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <h2>Our Rooms</h2>
                    <div class="bt-option">
                        <a href="./home.html">Home</a>
                        <span>Rooms</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="rooms-section spad">
    <div class="container">
        <div class="row">
            <input type="text" hidden value="@ViewBag.CheckIn" />
            <input type="text" hidden value="@ViewBag.CheckOut" />
            @foreach (var item in Model)
            {
                List<string> servicestr = new List<string>();
                <div class="col-lg-4 col-md-6">
                    <a asp-controller="TypeOfRoom" asp-action="RoomTypeDetail" asp-route-Id="@item.Id" asp-route-CheckIn="@ViewBag.CheckIn" asp-route-CheckOut="@ViewBag.CheckOut">
                        <div class="room-item">
                            <img src="~/images/@item.ImagePath" alt="" height="218">
                            <div class="ri-text">
                                <h4>@item.Name</h4>
                                <h3>@String.Format(info, "{0:#,##0 đ}", item.PricePerNight)<span>/đêm</span></h3>
                                <table>
                                    <tbody>
                                        <tr>
                                            <td class="r-o">Kích cỡ phòng:</td>
                                            <td>@item.Size<span>m<sup>2</sup></span></td>
                                        </tr>
                                        <tr>
                                            <td class="r-o">Số người lớn:</td>
                                            <td>@item.AmountAdults</td>
                                        </tr>
                                        <tr>
                                            <td class="r-o">Số trẻ em:</td>
                                            <td>@item.AmountChild</td>
                                        </tr>
                                        <tr>
                                            <td class="r-o">
                                                Dịch vụ:
                                            </td>
                                            <td>
                                                @if (item.ServiceViews.Count > 0)
                                                {
                                                    foreach (var service in item.ServiceViews.Take(3))
                                                    {
                                                        servicestr.Add(service.Name);
                                                    }
                                                }
                                                @String.Join(", ", servicestr)
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <span class="primary-btn">More Details</span>
                            </div>
                        </div>
                    </a>
                </div>
            }
            <div class="col-lg-12">
                <div class="room-pagination">
                    <a href="#">1</a>
                    <a href="#">2</a>
                    <a href="#">Next <i class="fa fa-long-arrow-right"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>

DatPhongDiWEB/DatPhongDiWeb/Views/TypeOfRoom/Detail.cshtml
@{
    Layout = "_LayoutThemesHotelBootraps";
}

<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <h2>Our Rooms</h2>
                    <div class="bt-option">
                        <a href="./home.html">Home</a>
                        <span>Rooms</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Section End -->
<!-- Room Details Section Begin -->
<section class="room-details-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="room-details-item">
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" style="width: 690px; height: 400px;">
                            <div class="item active">
                                <img src="~/sona-master/img/room/room-1.jpg" alt="" style="width: 690px; height: 400px;">
                            </div>

                            <div class="item">
                                <img src="~/sona-master/img/room/room-2.jpg" alt="" style="width: 690px; height: 400px;">
                            </div>

                            <div class="item">
                                <img src="~/sona-master/img/room/room-3.jpg" alt="" style="width: 690px; height: 400px;">
                            </div>
                        </div>

                        <!-- Left and right controls -->
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next" style="margin-right: 60px;">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <div class="rd-text">
                        <div class="rd-title">
                            <h3>Premium King Room</h3>
                            <div class="rdt-right">
                                <div class="rating">
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star-half_alt"></i>
                                </div>
                                <a href="#" style="margin-right: 60px;">Booking Now</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="room-details-item">
                    <div class="rd-text">
                        <h2>159$<span>/Pernight</span></h2>
                        <table>
                            <tbody>
                                <tr>
                                    <td class="r-o text-danger">Số phòng trống:</td>
                                    <td class="text-danger">5</td>
                                </tr>
                                <tr>
                                    <td class="r-o">Size:</td>
                                    <td>30 ft</td>
                                </tr>
                                <tr>
                                    <td class="r-o">Capacity:</td>
                                    <td>Max persion 5</td>
                                </tr>
                                <tr>
                                    <td class="r-o">Bed:</td>
                                    <td>King Beds</td>
                                </tr>
                                <tr>
                                    <td class="r-o">Services:</td>
                                    <td>Wifi, Television, Bathroom,...</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</section>
<!-- Room Details Section End -->

DatPhongDiWEB/DatPhongDiWeb/Views/TypeOfRoom/Index.cshtml
@{ Layout = "_LayoutAdmin"; }

<div class=" row">
    <a href="javascript:void(0);" class="btn btn-info" onclick="typeOfRoom.openModal()">Tạo mới</a>

    <table id="tbTypeOfRoom" class="table table-bordered mt-2">
        <thead class="thead-dark" style="text-align:center">
            <tr>
                <th>Mã loại phòng</th>
                <th>Tên loại phòng</th>
                <th>Người lớn</th>
                <th>Trẻ em</th>
                <th>Giá tiền</th>
                <th>Dịch vụ</th>
                <th>Trạng thái</th>
                <th>Thao tác</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

<!-- The Modal -->
<div class="modal" id="addEditTypeOfRoomModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Loại phòng</h4>
                <button type="button" class="close closeAddEditTypeOfRoomModal" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form id="frmAddEditTypeOfRoom">
                    <input hidden name="Id" id="Id" value="0" />
                    <div class="row form-group">
                        <label for="Name" class="col-3">Tên loại phòng</label>
                        <div class="col-9">
                            <input type="text" class="form-control" placeholder="Tên loại phòng"
                                   id="Name" name="Name"
                                   data-rule-required="true"
                                   data-msg-required="Tên loại phòng phải được nhập">
                        </div>
                    </div>

                    <div class="row form-group">
                        <label for="AmountAdults" class="col-3">Người lớn</label>
                        <div class="col-9">
                            <input type="number" class="form-control" placeholder="Số lượng người lớn"
                                   id="AmountAdults" name="AmountAdults"
                                   data-rule-required="true"
                                   data-msg-required="Số lượng người lớn phải được nhập">
                        </div>
                    </div>

                    <div class="row form-group">
                        <label for="AmountChild" class="col-3">Trẻ em</label>
                        <div class="col-9">
                            <input type="number" class="form-control" placeholder="Số lượng Trẻ em"
                                   id="AmountChild" name="AmountChild"
                                   data-rule-required="true"
                                   data-msg-required="Số lượng trẻ em phải được nhập">
                        </div>
                    </div>

                    <div class="row form-group">
                        <label for="PricePerNight" class="col-3">Giá tiền</label>
                        <div class="col-9">
                            <input type="number" class="form-control" placeholder="Giá tiền"
                                   id="PricePerNight" name="PricePerNight"
                                   data-rule-required="true"
                                   data-msg-required="Giá tiền phải được nhập">
                        </div>
                    </div>

                    <div class="row form-group" id="st">
                        <label for="Status" class="col-3">Trạng thái</label>
                        <div class="col-9">
                            <select class="form-control" id="Status" name="Status">
                            </select>
                        </div>
                    </div>

                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-success" onclick="typeOfRoom.save()">Lưu</a>
                <button type="button" class="btn btn-danger closeAddEditTypeOfRoomModal" data-dismiss="modal">Đóng lại</button>
            </div>

        </div>
    </div>
</div>

<div class="modal" id="ManagementImage" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title" id="TitleManagementImage"></h4>
                <input type="text" hidden name="name" value="" id="TypeofroomName"/>
                <button type="button" class="close closeManagementImage" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form enctype="multipart/form-data" id="UploadFile">
                    @Html.AntiForgeryToken()
                    <input type="number" id="typeOfRoomId" hidden />
                    <div class="form-group">
                        <input type="file" multiple class="form-control selectImage" id="images"
                               onchange="typeOfRoom.loadFile(event)" accept="image/*"/>
                    </div>
                    <div class="form-group">
                        <h3>Ảnh vừa chọn:</h3>
                        <div id="newImages">
                            <!--show Images befor upload-->

                        </div>

                        <h3>Ảnh đã có:</h3>
                        <div id="filelist">
                            <!--show Images by TypeOfRoomId-->
                        </div>
                    </div>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-success" onclick="typeOfRoom.UploadImages()">Upload ảnh</a>
                <button type="button" class="btn btn-danger closeManagementImage" data-dismiss="modal">Đóng lại</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="ManagementService">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Thêm dịch vụ vào loại phòng</h4>
                <button type="button" class="close closeManagementService" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form id="frmManagementService">
                    <input hidden name="TypeOfRoomId" id="TypeOfRoomId" value="0" />
                   <div class="row form-group">
                        <label for="ServiceId" class="col-3"><strong>Dịch vụ:</strong></label>
                        <div class="col-9">
                            <p id="ServiceId"></p>
                        </div>
                    </div>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-success" onclick="typeOfRoom.saveService()">Lưu</a>
                <button type="button" class="btn btn-danger closeManagementService" data-dismiss="modal">Đóng lại</button>
            </div>

        </div>
    </div>
</div>

<script src="~/js/typeOfRoom.js" asp-append-version="true"></script>